//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfVremeClient.ServiceReferenceVreme {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VremeDodatno", Namespace="http://schemas.datacontract.org/2004/07/_01_Vreme")]
    [System.SerializableAttribute()]
    public partial class VremeDodatno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PrvoPokretanjeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PrvoPokretanje {
            get {
                return this.PrvoPokretanjeField;
            }
            set {
                if ((this.PrvoPokretanjeField.Equals(value) != true)) {
                    this.PrvoPokretanjeField = value;
                    this.RaisePropertyChanged("PrvoPokretanje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVreme.IVreme", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IVreme {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVreme/GetVreme", ReplyAction="http://tempuri.org/IVreme/GetVremeResponse")]
        System.DateTime GetVreme();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVreme/GetVreme", ReplyAction="http://tempuri.org/IVreme/GetVremeResponse")]
        System.IAsyncResult BeginGetVreme(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndGetVreme(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVreme/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IVreme/GetDataUsingDataContractResponse")]
        WcfVremeClient.ServiceReferenceVreme.VremeDodatno GetDataUsingDataContract(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IVreme/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IVreme/GetDataUsingDataContractResponse")]
        System.IAsyncResult BeginGetDataUsingDataContract(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite, System.AsyncCallback callback, object asyncState);
        
        WcfVremeClient.ServiceReferenceVreme.VremeDodatno EndGetDataUsingDataContract(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVremeChannel : WcfVremeClient.ServiceReferenceVreme.IVreme, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetVremeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetVremeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WcfVremeClient.ServiceReferenceVreme.VremeDodatno Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WcfVremeClient.ServiceReferenceVreme.VremeDodatno)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VremeClient : System.ServiceModel.ClientBase<WcfVremeClient.ServiceReferenceVreme.IVreme>, WcfVremeClient.ServiceReferenceVreme.IVreme {
        
        private BeginOperationDelegate onBeginGetVremeDelegate;
        
        private EndOperationDelegate onEndGetVremeDelegate;
        
        private System.Threading.SendOrPostCallback onGetVremeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDataUsingDataContractDelegate;
        
        private EndOperationDelegate onEndGetDataUsingDataContractDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataUsingDataContractCompletedDelegate;
        
        public VremeClient() {
        }
        
        public VremeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VremeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VremeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VremeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetVremeCompletedEventArgs> GetVremeCompleted;
        
        public event System.EventHandler<GetDataUsingDataContractCompletedEventArgs> GetDataUsingDataContractCompleted;
        
        public System.DateTime GetVreme() {
            return base.Channel.GetVreme();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetVreme(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetVreme(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.DateTime EndGetVreme(System.IAsyncResult result) {
            return base.Channel.EndGetVreme(result);
        }
        
        private System.IAsyncResult OnBeginGetVreme(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetVreme(callback, asyncState);
        }
        
        private object[] OnEndGetVreme(System.IAsyncResult result) {
            System.DateTime retVal = this.EndGetVreme(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetVremeCompleted(object state) {
            if ((this.GetVremeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetVremeCompleted(this, new GetVremeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetVremeAsync() {
            this.GetVremeAsync(null);
        }
        
        public void GetVremeAsync(object userState) {
            if ((this.onBeginGetVremeDelegate == null)) {
                this.onBeginGetVremeDelegate = new BeginOperationDelegate(this.OnBeginGetVreme);
            }
            if ((this.onEndGetVremeDelegate == null)) {
                this.onEndGetVremeDelegate = new EndOperationDelegate(this.OnEndGetVreme);
            }
            if ((this.onGetVremeCompletedDelegate == null)) {
                this.onGetVremeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetVremeCompleted);
            }
            base.InvokeAsync(this.onBeginGetVremeDelegate, null, this.onEndGetVremeDelegate, this.onGetVremeCompletedDelegate, userState);
        }
        
        public WcfVremeClient.ServiceReferenceVreme.VremeDodatno GetDataUsingDataContract(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetDataUsingDataContract(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public WcfVremeClient.ServiceReferenceVreme.VremeDodatno EndGetDataUsingDataContract(System.IAsyncResult result) {
            return base.Channel.EndGetDataUsingDataContract(result);
        }
        
        private System.IAsyncResult OnBeginGetDataUsingDataContract(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite = ((WcfVremeClient.ServiceReferenceVreme.VremeDodatno)(inValues[0]));
            return this.BeginGetDataUsingDataContract(composite, callback, asyncState);
        }
        
        private object[] OnEndGetDataUsingDataContract(System.IAsyncResult result) {
            WcfVremeClient.ServiceReferenceVreme.VremeDodatno retVal = this.EndGetDataUsingDataContract(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataUsingDataContractCompleted(object state) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataUsingDataContractAsync(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        public void GetDataUsingDataContractAsync(WcfVremeClient.ServiceReferenceVreme.VremeDodatno composite, object userState) {
            if ((this.onBeginGetDataUsingDataContractDelegate == null)) {
                this.onBeginGetDataUsingDataContractDelegate = new BeginOperationDelegate(this.OnBeginGetDataUsingDataContract);
            }
            if ((this.onEndGetDataUsingDataContractDelegate == null)) {
                this.onEndGetDataUsingDataContractDelegate = new EndOperationDelegate(this.OnEndGetDataUsingDataContract);
            }
            if ((this.onGetDataUsingDataContractCompletedDelegate == null)) {
                this.onGetDataUsingDataContractCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataUsingDataContractDelegate, new object[] {
                        composite}, this.onEndGetDataUsingDataContractDelegate, this.onGetDataUsingDataContractCompletedDelegate, userState);
        }
    }
}
